baseURL = 'https:/sanityseeker.github.io/belfilm'
languageCode = 'en-us'
title = 'belfilm'
theme = "hugo-theme-console"
timeout = 10000000
publishDir = "docs"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

