baseURL = 'https://belfilm.onrender.com/'
languageCode = 'en-us'
title = 'album@belfilm'
theme = "hugo-theme-console"
timeout = 10000000
publishDir = "docs"
enableGitInfo = true

[frontmatter]
  date = ['lastmod', 'date']
  lastmod = [':git', ':fileModTime', ':default', 'date']

DefaultContentLanguage = "en"
[languages]
  [languages.en]
    languageName = "English"
    weight = 1
  [languages.ru]
    languageName = "Русский"
    weight = 2
  
#  defaultContentLanguageInSubdir = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

