baseURL = 'https://belfilm.onrender.com/'
languageCode = 'en-us'
title = 'album@belfilm'
theme = "hugo-theme-console"
timeout = 10000000
publishDir = "docs"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

