baseURL = 'https://192.168.10.130/belfilm/'
languageCode = 'en-us'
title = 'belfilm'
theme = "hugo-theme-console"
timeout = 10000000

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

